app = "weblog-app"
primary_region = "iad"

[build]

[env]
  PORT = "8080"
  COOKIE_SECURE = "true"

[[mounts]]
  source = "weblog_uploads"
  destination = "/app/web/static/uploads"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0

[[vm]]
  memory = "256mb"
  cpu_kind = "shared"
  cpus = 1
